# Generated by Django 5.2 on 2025-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeapplication',
            name='cover_letter',
        ),
    ]
