# Generated by Django 5.2 on 2025-05-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_status_alter_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeapplication',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeapplication',
            name='seminars',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
