# Generated by Django 5.2 on 2025-05-04 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_resumeapplication_references_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_match', models.CharField(max_length=100)),
                ('aspiration_score', models.FloatField()),
                ('ability_score', models.FloatField()),
                ('engagement_score', models.FloatField()),
                ('aea_total', models.FloatField()),
                ('education_score', models.FloatField()),
                ('experience_score', models.FloatField()),
                ('final_score', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='jobs.resumeapplication')),
            ],
        ),
    ]
