# Generated by Django 5.2 on 2025-05-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_resumescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='ability_competency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='ability_learning',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='aspiration_behavioral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='aspiration_motivational',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='engagement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='ability_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='aea_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='aspiration_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='education_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='engagement_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resumescore',
            name='final_score',
            field=models.FloatField(default=0.0),
        ),
    ]
