# Generated by Django 5.2 on 2025-05-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_resumescore_ability_competency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescore',
            name='effective_ability_max',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='effective_aea_max',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='effective_aspiration_max',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='effective_engagement_max',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='resumescore',
            name='effective_total_max',
            field=models.FloatField(default=105.0),
        ),
    ]
