# Generated by Django 5.2.1 on 2025-05-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_resumescore_effective_ability_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='posted_date',
            new_name='date_posted',
        ),
    ]
