# Generated by Django 5.2.1 on 2025-05-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_rename_posted_date_job_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_posted',
            new_name='posted_date',
        ),
        migrations.AddField(
            model_name='resumeapplication',
            name='traits',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
