# Generated by Django 5.2.1 on 2025-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_date_posted_job_posted_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeapplication',
            old_name='objective',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='resumescore',
            old_name='ability_competency',
            new_name='qualifications_score',
        ),
        migrations.RenameField(
            model_name='resumescore',
            old_name='ability_learning',
            new_name='skills_score',
        ),
        migrations.RemoveField(
            model_name='resumeapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resumeapplication',
            name='experiences',
        ),
        migrations.RemoveField(
            model_name='resumeapplication',
            name='references',
        ),
        migrations.RemoveField(
            model_name='resumeapplication',
            name='seminars',
        ),
        migrations.RemoveField(
            model_name='resumeapplication',
            name='traits',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='ability_score',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='aea_total',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='aspiration_behavioral',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='aspiration_motivational',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='aspiration_score',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='education_score',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='effective_ability_max',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='effective_aea_max',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='effective_aspiration_max',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='effective_engagement_max',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='effective_total_max',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='resumescore',
            name='engagement_score',
        ),
        migrations.AddField(
            model_name='resumeapplication',
            name='qualifications',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumeapplication',
            name='skills',
            field=models.TextField(),
        ),
    ]
