# Generated by Django 5.2.1 on 2025-05-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_fix_skills_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
