# Generated by Django 5.2.1 on 2025-05-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_experience_required_job_qualifications_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeapplication',
            name='eligibility',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumeapplication',
            name='training_hours',
            field=models.IntegerField(default=0),
        ),
    ]
